// MTPPSCRANET, Version=1.0.0.18, Culture=neutral, PublicKeyToken=null
// MTPPSCRANET.ERROR
internal enum ERROR
{
	ERROR_NO_ERR = 0,
	ERROR_UNKNOWN = 255,
	ERROR_BUFFER_INSUFFICIENT = 13,
	ERROR_DEVICE_NOT_OPEN = 5,
	ERROR_DEVICE_TIMEOUT = 1,
	ERROR_INVALID_PARAMETERS = 6,
	ERROR_DEVICE_NOT_SUPPORT = 7,
	ERROR_DEVICE_ERROR = 7,
	ERROR_CARD_NOT_SUPPORT = 9,
	ERROR_BAD_CARD = 9,
	ERROR_IPAD_DEVICE_REMOVED = 4,
	ERROR_BUSY_IN_PRIOR_COMMAND = 15,
	ERROR_NO_SIGNATURE = 16,
	ERROR_USER_CANCEL = 2
}
