// MTLib, Version=1.0.22.1, Culture=neutral, PublicKeyToken=null
// MTLIB.MTCardDataError
public enum MTCardDataError
{
	INTRA_PACKET_TIMEOUT,
	INTER_PACKET_TIMEOUT,
	TRANSACTION_ERROR,
	PACKET_ERROR,
	MISSING_PACKET_ERROR,
	CHECKSUM_ERROR
}
